---
# Tunnel
# Matched details from `config vpn ipsec phase1-interface` then `get tunnel`
- name: Configure Phase 1 Interface for VPN IPSec Tunnel
  fortinet.fortios.fortios_vpn_ipsec_phase1_interface:
    vdom: "root"
    state: "present"
    access_token: "{{ access_token }}"
    vpn_ipsec_phase1_interface:
      name: "tunnel"
      type: "static"
      interface: "wan1"
      ip_version: "4"
      ike_version: "2"
      local_gw: "0.0.0.0"
      keylife: "28800"
      authmethod: "psk"
      authmethod_remote: "psk"
      peertype: "any"
      net_device: "disable"
      passive_mode: "disable"
      exchange_interface_ip: "disable"
      aggregate_member: "disable"
      mode_cfg: "disable"
      proposal: "aes256-sha384"
      localid: ""
      localid_type: "auto"
      auto_negotiate: "enable"
      negotiate_timeout: "30"
      fragmentation: "enable"
      ip_fragmentation: "post-encapsulation"
      dpd: "on-demand"
      forticlient_enforcement: "disable"
      comments: ""
      dhgrp: "21"
      suite_b: "disable"
      eap: "disable"
      ppk: "disable"
      wizard_type: "custom"
      reauth: "disable"
      idle_timeout: "disable"
      ha_sync_esp_seqno: "enable"
      auto_discovery_sender: "disable"
      auto_discovery_receiver: "disable"
      auto_discovery_forwarder: "disable"
      encapsulation: "none"
      nattraversal: "disable"
      fragmentation_mtu: "1200"
      childless_ike: "disable"
      rekey: "enable"
      fec_egress: "disable"
      fec_ingress: "disable"
      network_overlay: "disable"
      remote_gw: "192.168.1.249"
      monitor: ""
      tunnel_search: "selectors"
      add_gw_route: "disable"
      psksecret: "secretkey"
      dpd_retrycount: "3"
      dpd_retryinterval: "20"

# Matched details from `config vpn ipsec phase1-interface` then `get tunnel`
- name: Configure Phase 2 Interface for VPN IPSec Tunnel
  fortinet.fortios.fortios_vpn_ipsec_phase2_interface:
    vdom: "root"
    state: "present"
    access_token: "{{ access_token }}"
    vpn_ipsec_phase2_interface:
      name: "tunnel"
      phase1name: "tunnel"
      proposal: "aes256-sha384"
      pfs: "enable"
      ipv4_df: "disable"
      dhgrp: "21"
      replay: "enable"
      keepalive: "disable"
      auto_negotiate: "disable"
      auto_discovery_sender: "phase1"
      auto_discovery_forwarder: "phase1"
      keylife_type: "seconds"
      encapsulation: "tunnel-mode"
      comments: ""
      protocol: "0"
      src_addr_type: "subnet"
      src_port: "0"
      dst_addr_type: "subnet"
      dst_port: "0"
      keylifeseconds: "43200"
      src_subnet: "192.168.3.0 255.255.255.0"
      dst_subnet: "192.168.2.0 255.255.255.0"
        